<a href="https://colab.research.google.com/github/anderomeda371/firstrepo/blob/main/tensorflow_keras(first)_prediction_of_bank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [147]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import pandas as pd

In [148]:
tf.__version__


'2.12.0'

In [149]:
dataset=pd.read_csv("/content/Churn_Modelling.csv")
X=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values


In [150]:
X[0]

array([619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [151]:
X[0]
test=[600,'France',"Male",40,3,60000,2,1,1,50000]
df=pd.DataFrame([600,'France',"Male",40,3,60000,2,1,1,50000])
test=np.array(test)
df=np.array(df)
df=df.reshape(1,10)
df.shape
df[:,2]

array(['Male'], dtype=object)

In [152]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])

In [153]:
X[0]

array([619, 'France', 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [154]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct=ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[1])],remainder="passthrough")
X=np.array(ct.fit_transform(X))

In [155]:
X[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [156]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [157]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [158]:
ann=tf.keras.models.Sequential()

In [159]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

In [160]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

In [161]:
#output channel

ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

In [162]:
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [164]:
ann.fit(X_train,y_train,batch_size=32,epochs=10)

Epoch 1/10
250/250 [==============================] - 1s 4ms/step - loss: 0.3546 - accuracy: 0.8547
Epoch 2/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3521 - accuracy: 0.8544
Epoch 3/10
250/250 [==============================] - 1s 3ms/step - loss: 0.3492 - accuracy: 0.8569
Epoch 4/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3480 - accuracy: 0.8597
Epoch 5/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3465 - accuracy: 0.8589
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3448 - accuracy: 0.8626
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3442 - accuracy: 0.8615
Epoch 8/10
250/250 [==============================] - 0s 2ms/step - loss: 0.3429 - accuracy: 0.8622
Epoch 9/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3420 - accuracy: 0.8618
Epoch 10/10
250/250 [==============================] - 1s 2ms/step - loss: 0.3414 - accuracy: 0.8625

In [167]:
ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))

1/1 [==============================] - 0s 141ms/step


array([[0.04052857]], dtype=float32)

In [221]:
y_predict=ann.predict(X_test)
type(y_predict)
convert_func=np.vectorize(lambda x: 1 if x>0.5 else 0)
# print(y_predict,y_test.reshape(-1,1))
y_predict=convert_func(y_predict)
from sklearn.metrics import accuracy_score,confusion_matrix
y_test=y_test.reshape(-1,1)
# y_predict.shape,y_test.reshape(-1,1).shape
accuracy_score(y_test,y_predict)
matrix=confusion_matrix(y_test,y_predict)
matrix
# print(np.concatenate((y_test,y_predict),axis=1))
# print(f"{y_predict.shape},{type(y_predict)}....{y_test.shape},{type(y_test)}")
# for i in range(len(y_predict)):
#   print(y_test[i],y_predict[i])
# y_test,y_predict

63/63 [==============================] - 0s 3ms/step


array([[1503,   92],
       [ 185,  220]])